# Generated by Django 2.2 on 2020-01-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, max_length=5, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'a+'), ('O+', 'o+'), ('B+', 'b+'), ('AB+', 'ab+'), ('A-', 'a-'), ('O-', 'o-'), ('B-', 'b-'), ('AB-', 'ab-')], max_length=4, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.IntegerField(blank=True, null=True)),
                ('physical_disorders', models.BooleanField(default=False)),
                ('mental_disorders', models.BooleanField(default=False)),
                ('major_surgeries', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('heart_attack', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('regular_medicine', models.CharField(blank=True, max_length=100)),
                ('drug_allergies', models.CharField(blank=True, max_length=200)),
                ('comments', models.CharField(blank=True, max_length=300)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
            ],
        ),
    ]
