# Generated by Django 2.2 on 2020-02-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200213_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
