# Generated by Django 2.2 on 2020-01-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('dentist', 'Dentist'), ('general physician', 'General Physician'), ('pediatrician', 'Pediatrician'), ('ayurveda', 'Ayurveda'), ('orthopedist', 'Orthopedist'), ('dental surgeon', 'Dental Surgeon'), ('dermatologist', 'Dermatologist'), ('general surgeon', 'General Surgeon'), ('gynecologist', 'Gynecologist')], max_length=20)),
                ('registration_no', models.CharField(max_length=20)),
                ('council', models.CharField(choices=[('tamil nadu medical council', 'Tamil Nadu Medical Council'), ('medical council of india', 'Medical Council of India'), ('andhra pradesh medical council', 'Andhra Pradesh Medical Council'), ('assam medical council', 'Assam Medical Council'), ('bhopal medical council', 'Bhopal Medical Council'), ('bihar medical council', 'Bihar Medical Council'), ('bombay medical council', 'Bombay Medical Council'), ('chandigarh medical council', 'Chandigarh Medical Council'), ('chattisgarh medical council', 'Chattisgarh Medical Council'), ('delhi medical council', 'Delhi Medical Council'), ('gujarat medical council', 'Gujarat Medical Council'), ('goa medical council', 'Goa Medical Council'), ('haryana medical council', 'Haryana Medical Council'), ('hyderabad medical council', 'Hyderabad Medical Council')], max_length=50)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
                ('collage', models.CharField(max_length=80)),
                ('year_completion', models.IntegerField(null=True)),
                ('doctor_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='doctor.DoctorProfile')),
            ],
        ),
    ]
