# Generated by Django 2.2 on 2020-01-31 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_hospital_user'),
        ('patient', '0003_delete_appointment'),
        ('doctor', '0003_auto_20200131_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('canceled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_cancel', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_create', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_id', to='doctor.DoctorProfile')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_id', to='hospital.Hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='patient.Patient')),
                ('time_slot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='doctor.DocTimeSlot')),
            ],
        ),
    ]
