# Generated by Django 2.2 on 2020-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], max_length=10, null=True),
        ),
    ]
