# Generated by Django 2.2 on 2020-02-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], max_length=10, null=True),
        ),
    ]
