# Generated by Django 2.2 on 2020-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20200203_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checkup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
