# Generated by Django 2.2 on 2020-02-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_appointment_checkup_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='checkup_time',
        ),
    ]
