# Generated by Django 2.2 on 2020-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_checkuptiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='collage',
            new_name='university',
        ),
    ]
